#! /bin/sh

/home/widr1225/.config/bspwm/panel &

bspc config border_width        4
bspc config window_gap          8
bspc config top_padding        30

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor LVDS1 -d I II III IV V

feh --bg-fill /home/widr1225/Pictures/bg.jpg
compton -cCGfFb -o 0.38 -O 200 -I 200 -t 0 -l 0 -r 3 -D2 -m 0.88
