#!/bin/bash
#
# Bar Ain't Recursive panel
# by Ivan Sokolov
#

WHITE=ECF0F1
RED=E74C3C
GREEN=2ECC71
BLACK=1A1A1A
GRAY=606060
BLUE=3498DB

function A {
	echo -n "%{A:$2:}$1%{A}"
}

function B {
	echo -n "%{B#ff$2}$1%{B-}"
}

function F {
	echo -n "%{F#ff$2}$1%{F-}"
}

function o {
	echo "%{+o}$1%{-o}"
}

function u {
	echo "%{+u}$1%{-u}"
}

###

DIV=$(F '|' $GRAY)

###

network() {
	ping -c 1 8.8.8.8 >/dev/null 2>&1 && echo -n $(F + $GREEN) || echo -n $(F - $RED)
}

calendar() {
    DATE=$(date +"%m-%d-%y")
	echo -n $(F $DATE $WHITE)
}

clock() {
	TIME=$(date +%I:%M%p)
	echo -n $(F $TIME $WHITE)
}

volume() {
	VOLUME=$(pamixer --get-volume)
	if [[ $(pamixer --get-mute) -eq 'true' ]]
	then
		VCOLOR=$WHITE
	else
		VCOLOR=$RED
	fi
	echo -n "$(A $(F $VOLUME $VCOLOR) volume)"
}

battery() {
	BATTERY=$(acpi -b | awk '{gsub(/%,/,""); print $4}' | sed 's/%//g')
	if [[ $BATTERY -gt 20 ]]
	then
		BCOLOR=$WHITE
	else
		BCOLOR=$RED
	fi
	echo -n $(F $BATTERY ff$BCOLOR)
}

layout() {
	echo -n "$(A $(F $(xkb-switch) $WHITE) layout)"
}

mpc_status() {
	if [[ -n $(mpc | grep playing) ]]
	then
		echo -n "$(F "$(mpc current -f "[%title%]")" $WHITE) $DIV "
		echo -n "$(F "$(mpc current -f "[%album%]")" $WHITE) $DIV "
		echo -n "$(F "$(mpc current -f "[%artist%]")" $WHITE) "
	else
		echo -n ''
	fi
}

#		echo -n "$(F "$(mpc current -f "[%title% $(F - $GRAY) %album% $(F - $GRAY) %artist%]|[%file%]")" $WHITE)"

mpc_controls() {
	echo -n ''
}

while true
do
	# Left
	printf '%s' '%{l}'
	# Desktops
	for i in VI VII VIII IX X
	do

      if [[ $(bspc control --get-status | grep -c O$i:) -eq 'true' ]]
      then
          COLOR=$WHITE
      else
          COLOR=$BLUE
      fi
		printf ' %s' "%{A:$i:}$(F \| $GRAY)$(F $i $COLOR)$(F \| $GRAY)%{A}"
	done
	
	# Center
	# printf '%s' '%{c}'
	# printf '%s' "$(mpc_status)"
	# printf '%s' "$(mpc_controls)"
	
	# Right
	printf '%s' '%{r}'
	printf ' %s' $(network) $DIV 
	# printf ' %s' $(layout) $DIV
	printf ' %s' $(volume) $DIV 
	printf ' %s' $(battery) $DIV 
	printf ' %s' $(clock)
	printf ' %s' $(calendar) $DIV
	printf ' %s \n' "$(A "$(F "*" "$RED")" 'bspc quit')"

	sleep .5s
done | bar \
	-F \#ff$WHITE \
	-B \#ff$BLACK \
	-g 1700x20+1610+10 \
	-f '-*-terminus-medium-r-normal-*-14-*-*-*-*-*-*-u' | ~/.config/bspwm/spawner2
