#!/bin/bash
#
# Spawner for Bar Ain't Recursive
#

while read cmd
do
	case "$cmd" in
		volume) pamixer --toggle-mute ;;
		layout) xkb-switch --next ;;
		     I) bspc desktop -f ^1 ;;
            II) bspc desktop -f ^2 ;;
           III) bspc desktop -f ^3 ;;
            IV) bspc desktop -f ^4 ;;
             V) bspc desktop -f ^5 ;;
		     *) $cmd ;;
	esac
done
